import { ConnectButton } from "@rainbow-me/rainbowkit"
import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />

      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="https://rmrk.app">RMRK!</a>
        </h1>

        <p className={styles.description}>To get started try one of these and mint an NFT:</p>
        <h2 className={styles.description}>
          <a href="/nesting">Nesting </a>
          or
          <a href="/multi-resource"> Multi-resource</a>
        </h2>

        <div className={styles.grid}>
          <a href="/nesting" className={styles.card}>
            <h2>Nesting Demo &rarr;</h2>
            <p>Make your NFT own other NFTs.</p>
          </a>

          <a href="/multi-resource" className={styles.card}>
            <h2>Multi-resource Demo &rarr;</h2>
            <p>Multiple file types inside one NFT.</p>
          </a>

          <a href="/equippable" className={styles.card}>
            <h2>Equippable NFTs Demo &rarr;</h2>
            <p>Equip items to your NFT characters.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
