import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useConnect, useEnsName } from "wagmi"
import { InjectedConnector } from "@wagmi/core"

const MultiResource: NextPage = () => {

  const { address, isConnected } = useAccount()
  const { data: ensName } = useEnsName({ address })
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  })


  return (
    <div className={styles.container}>
      <Head>
        <title>RMRK Multi-resource App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Multi-resource Demo
        </h1>

        <p className={styles.description}>Mint an NFT and attach additional resources below:</p>

        <button className={styles.button}>Mint NFT</button>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
};

export default MultiResource;
